apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/sn-labs-lamchitaia1/accounts:1
        name: accounts
        ports:
        - containerPort: 8080
